### ISSUE TITLE
Can't install netbird addon on Home ASsistant:

### ISSUE THREAD

**Issue by DriedPlumber** [netbirdio/addon-netbird#105]
Home Assistant

Core: 2024.5.4
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

When I try to install addon from NetBird Home Assistant Add-ons, I get next message:

Failed to install add-on
The command '/bin/bash -o pipefail -c apk add --no-cache nftables=1.0.9-r1' returned a non-zero code: 1

I'm trying to install v0.27.8
Previous version worked without problem...

Is there any solution to this problme?

Thx a lot for any info!

**Comment by lfarkas** [comment]
thanks.
fixed in the latest version.

**Comment by DriedPlumber** [comment]
Thank you for your time!

I just tried one more time and I get same error, I'm not able to update addon in home assistant:
In logs I can see next message:

2024-05-24T00:36:04+02:00 WARN management/client/grpc.go:162: disconnected from the Management service but will retry silently. Reason: rpc error: code = Unknown desc = account not found: index lookup failed

Even if the addon is stoped, logs keep coming which is strange....it looks like addon is not stoped

![image](https://github.com/netbirdio/addon-netbird/assets/120777990/5295280b-bb7c-4386-92e3-b930b8b61487)


![image](https://github.com/netbirdio/addon-netbird/assets/120777990/926d97c4-e842-4036-88c6-aaa16197f724)

**Comment by lfarkas** [comment]
you should have to check ie update the update (settings/addon/<top right corner> check for update clock icon.

**Comment by mlsmaycon** [comment]
@DriedPlumber it seems like your management system is outdated. Can you confirm if you are running a self-hosted version or cloud hosted?

**Comment by DriedPlumber** [comment]
@mlsmaycon
I'm running Home Assistant on raspberry 4 and it  is a Home Assistant Operating system. I tried to reset, reboot, uninstall, reinstall but I'm not able to update netbird addon or to install it after I uninstalled it.
I always get /bin/bash -o pipefail error. 

I'm going to uninstall this addon and I will go via tailscape road. This never happened to me with any addon that I used with Home Assistant. Netbird addon Version 27.7  worked without any problem and after I tried to update netbird everything went down. Most surprising thing to me is that even I stopped netbird addon I still receive logs...

My homeassistant is up to date!

Last night I uninstalled netbird from my home assistant and today I will destroy my VPC on digitalocean with netbird as I was not able to fix this issue. 

I tried to install tailscape in home assistant and everything works great. So I will move myself to headscape today.

 
Thx for your time people

**Comment by mlsmaycon** [comment]
Hi @DriedPlumber so you were using self-hosted netbird. 
There was an issue fixed with the server version 0.27.8. The cloud version was updated and it should happen there.

The problem was caused when you deleted a peer from the system, and the peer didn't receive a proper response from the server, causing endless retries.  Upgrading should fix it if you still want to validate it with NetBird.

**Comment by DriedPlumber** [comment]
Yes, I want to keep using netbird....I started to love it....

I will try again today when I get back from work and I will post results here.

Thank you very much for your time and effort mlsmaycon!

**Comment by mlsmaycon** [comment]
That's great, please check the upgrade docs here: 

If you followed the advanced guide: https://docs.netbird.io/selfhosted/selfhosted-guide#upgrade
If you followed the quick start guide: https://docs.netbird.io/selfhosted/selfhosted-quickstart#upgrade

**Comment by mlsmaycon** [comment]
That's awesome!! Thanks for the feedback.
