### ISSUE TITLE
Unable to install on HAOS 12.4

### ISSUE THREAD

**Issue by prakai** [netbirdio/addon-netbird#118]
# Problem
Install failed on HAOS 12.4. Error message is: 

Failed to install add-on
The command '/bin/bash -o pipefail -c apk add --no-cache nftables=1.0.9-r2' returned a non-zero code: 1

# Homeassistant version
Core: 2024.7.2
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240710.0

**Comment by lfarkas** [comment]
there must be an error on your side. this is the correct version:
https://pkgs.alpinelinux.org/packages?name=nftables&branch=v3.20&repo=&arch=&maintainer=
try again

**Comment by prakai** [comment]
I have try to test with 3 commands directly on home assistant shell: 
 1) `apk add --no-cache nftables=1.0.9-r2` - its success
 2) `/bin/bash -o pipefail -c apk add --no-cache nftables=1.0.9-r2` - its failure
 3) `/bin/bash -o pipefail -c 'apk add --no-cache nftables=1.0.9-r2'` - its success

I think, the problem is caused by running commands in the Dockerfile.

```
#----
#netbird/Dockerfile
#-----

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3003
RUN \
    apk add --no-cache \
    nftables=1.0.9-r2
```

**Comment by lfarkas** [comment]
it has nothing to do with home assistant shell. it's running during docker build INSIDE the container, but i changed a bit the Dockerfile try the latest version.

**Comment by lfarkas** [comment]
probably fixed since no response

**Comment by prakai** [comment]
I think the problem is caused by its conflict with the Old Netbird Client.
I installed the Old Netbird Client add-on first, then I found this add-on. I removed the old add-on and then installed any version of this add-on, but I got the same error message.
I have other Home Assistant hosts. I can install this add-on on those hosts without error.
