### ISSUE TITLE
Unable to save extra environment variables

### ISSUE THREAD

**Issue by kreisklasse** [netbirdio/addon-netbird#144]
_Add-on: NetBird
 Add-on version: v0.29.4
 System: Home Assistant OS 13.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2024.9.2
 Home Assistant Supervisor: 2024.09.1_

# Problem/Motivation

> Unable to save extra environment variables like 
" --enable-rosenpass --rosenpass-permissive"

**So what is the correct way to enter extra variables ?**

## Actual behavior

> Configuration was not saved with error message:
_**Invalid list for option 'env_vars' in NetBird**_

## Steps to reproduce

> copy variables (in several ways) like 
--enable-rosenpass --rosenpass-permissive
in "Extra environment variables" and try to save configuration

## Workaround
> With the File Editor in Home-Assistant you can change some values at
_/homeassistant/netbird/config.json_

**Comment by lfarkas** [comment]
added support for rosenpass in the next version...
