### ISSUE TITLE
Does not maintain IP and access while update from 0.29.4 to 0.30.0

### ISSUE THREAD

**Issue by kreisklasse** [netbirdio/addon-netbird#148]
_Home Assistant
Core - 2024.10.0
Supervisor - 2024.09.1
Operating System - 13.1
Frontend - 20241002.2
Netbird AddOn - v0.30.0_

# Problem

> Updating the addon from 0.29.4 to 0.30.0 in HA via the standard update procedure,
the netbird addon is requesting again new access via the link in the cli.
So HA gets a new netbird IP and a second entry in the peer list.
And netbird addon version 0.30 seems not to recognize/read _config.json_ at   /homeassistant/netbird/config.json  anymore.

## Expected behavior

> during updates in the 0.29.x versions there was no request of re-authenticating the peer after an update. HA addon kept the netbird IP. And also accepted changes in the _config.json_.

**Comment by kreisklasse** [comment]
Ok, found this https://github.com/netbirdio/addon-netbird/pull/145 were the change of the storage of the _config.json_ is described.

Probably this caused the behavior I described above.

Would be nice to have _Release Notes_ in the add-on and here on GitHub.

**Comment by lfarkas** [comment]
`mv /mnt/data/supervisor/homeassistant/netbird/config.json /mnt/data/supervisor/addon_configs/7edd9457_netbird/config.json`
or simple in a terminal:
`mv homeassistant/netbird/config.json addon_configs/7edd9457_netbird/config.json`
in the next version i try to fix it

**Comment by lfarkas** [comment]
v0.30.0.1 fix it
